In [1]:
import pandas

In [3]:
import pandas as pd

In [2]:
import openpyxl

In [5]:
pd.read_excel("2025.xlsx")

,SN,City,Municipality,Date&Time,Longitude,Latitude,Damage,Type,Description
0,1510533,BEOGRAD,BARAJEVO,"05.01.2025,18:50",20.366175,44.619215,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Ostali sudari sa parkiranim vozilom
1,1508366,BEOGRAD,BARAJEVO,"06.01.2025,01:00",20.351757,44.604264,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Sudar sa parkiranim vozilom sa leve strane kol...
2,1510854,BEOGRAD,BARAJEVO,"06.01.2025,16:30",20.342381,44.588294,Sa povredjenim,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću istim putem ...
3,1511079,BEOGRAD,BARAJEVO,"09.01.2025,13:05",20.366297,44.618967,Sa mat.stetom,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću istim putem ...
4,1508796,BEOGRAD,BARAJEVO,"11.01.2025,02:30",20.413140,44.607341,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgode sa učešćem jednog vozila i životinja
...,...,...,...,...,...,...,...,...,...
33410,1556401,ŠABAC,ŠABAC,"25.12.2025,06:20",19.717414,44.746909,Sa povredjenim,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...
33411,1556391,ŠABAC,ŠABAC,"25.12.2025,18:20",19.669970,44.778275,Sa povredjenim,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...
33412,1556667,ŠABAC,ŠABAC,"27.12.2025,17:25",19.352593,44.705596,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgode sa učešćem jednog vozila i životinja
33413,1556679,ŠABAC,ŠABAC,"28.12.2025,00:10",19.611194,44.732849,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak udesno sa ...
33414,1556707,ŠABAC,ŠABAC,"28.12.2025,05:30",19.404270,44.460260,Sa povredjenim,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...

In [7]:
df=pd.read_excel("2025.xlsx")

In [8]:
df['Damage'].value_counts()

Damage
Sa mat.stetom     19819
Sa povredjenim    13133
Sa poginulim        463
Name: count, dtype: int64

In [9]:
df['Type'].value_counts()

Type
SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA             9702
SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PRELAZAK    8221
SN SA JEDNIM VOZILOM                                  7673
SN SA PARKIRANIM VOZILIMA                             5244
SN SA PEŠACIMA                                        2575
Name: count, dtype: int64

In [10]:
df['Description'].value_counts()

Description
Najmanje dva vozila koja se kreću u istom smeru – sustizanje                                                   3943
Sudar sa parkiranim vozilom sa desne strane kolovoza                                                           2554
Ostale nezgode sa najmanje dva vozila – suprotni smerovi bez skretanja                                         1571
Nezgoda sa jednim vozilom – silazak udesno sa kolovoza na pravcu                                               1528
Najmanje dva vozila koja se kreću istim putem u suprotnim smerovima uz skretanje ulevo ispred drugog vozila    1434
                                                                                                               ...
Nezgode sa učešćem šinskog i drumskog vozila                                                                     17
Prelazak pešaka preko kolovoza sa skretanjem vozila udesno, u raskrsnici                                         16
Pešak se na trotoaru ili biciklističkoj stazi kreće suprotno od smera kretanja vozila                            15
Prelazak pešaka preko kolovoza (sleva ili zdesna), sa skretanjem vozila (levo ili desno), u raskrsnici            9
Najmanje dva vozila koja se kreću istim putem u suprotnim smerovima i vrše skretanje na naspramne puteve          9
Name: count, Length: 68, dtype: int64

In [11]:
df[df['Damage'] == 'Sa poginulim']

,SN,City,Municipality,Date&Time,Longitude,Latitude,Damage,Type,Description
39,1522423,BEOGRAD,BARAJEVO,"20.04.2025,12:30",20.348168,44.547093,Sa poginulim,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak udesno sa ...
51,1524259,BEOGRAD,BARAJEVO,"10.05.2025,04:20",20.377262,44.539612,Sa poginulim,SN SA JEDNIM VOZILOM,Nezgode sa učešćem šinskog i drumskog vozila
112,1544798,BEOGRAD,BARAJEVO,"11.09.2025,05:15",20.430054,44.556956,Sa poginulim,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak udesno sa ...
130,1547276,BEOGRAD,BARAJEVO,"21.10.2025,01:55",20.445037,44.553434,Sa poginulim,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak udesno sa ...
159,1556559,BEOGRAD,BARAJEVO,"25.12.2025,10:55",20.402628,44.634977,Sa poginulim,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...
...,...,...,...,...,...,...,...,...,...
33145,1532525,ŠABAC,ŠABAC,"11.07.2025,12:30",19.487325,44.735780,Sa poginulim,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom i prevrtanjem
33147,1532529,ŠABAC,ŠABAC,"11.07.2025,11:40",19.642692,44.622178,Sa poginulim,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak sa kolovoz...
33190,1535798,ŠABAC,ŠABAC,"02.08.2025,03:30",19.601294,44.769074,Sa poginulim,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila – čeoni sudar
33301,1544961,ŠABAC,ŠABAC,"07.10.2025,07:00",19.612737,44.733892,Sa poginulim,SN SA PEŠACIMA,Pešak se kreće duž kolovoza u smeru kretanja v...
33342,1549410,ŠABAC,ŠABAC,"07.11.2025,22:40",19.508076,44.718980,Sa poginulim,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak sa kolovoz...

In [13]:
df.groupby('Damage')['Type']

In [15]:
(
    df
    ["Damage"]
    .value_counts()
    .to_frame("SN")
)

                   SN
Damage
Sa mat.stetom   19819
Sa povredjenim  13133
Sa poginulim      463

In [21]:
df['Date&Time'] = pd.to_datetime(df['Date&Time'])
df['Date'] = df['Date&Time'].dt.date
df['Time'] = df['Date&Time'].dt.time

/var/folders/5_/w6x2qs2n2dsg6mgnhkrxnzg00000gn/T/ipykernel_2105/1639901837.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date&Time'] = pd.to_datetime(df['Date&Time'])

In [22]:
df.head()

,SN,City,Municipality,Date&Time,Longitude,Latitude,Damage,Type,Description,Date,Time
0,1510533,BEOGRAD,BARAJEVO,2025-05-01 18:50:00,20.366175,44.619215,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Ostali sudari sa parkiranim vozilom,2025-05-01,18:50:00
1,1508366,BEOGRAD,BARAJEVO,2025-06-01 01:00:00,20.351757,44.604264,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Sudar sa parkiranim vozilom sa leve strane kol...,2025-06-01,01:00:00
2,1510854,BEOGRAD,BARAJEVO,2025-06-01 16:30:00,20.342381,44.588294,Sa povredjenim,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću istim putem ...,2025-06-01,16:30:00
3,1511079,BEOGRAD,BARAJEVO,2025-09-01 13:05:00,20.366297,44.618967,Sa mat.stetom,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću istim putem ...,2025-09-01,13:05:00
4,1508796,BEOGRAD,BARAJEVO,2025-11-01 02:30:00,20.413140,44.607341,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgode sa učešćem jednog vozila i životinja,2025-11-01,02:30:00

In [23]:
(
    df
    ["Date"]
    .value_counts()
    .to_frame("SN")
)

             SN
Date
2025-03-10  143
2025-08-11  131
2025-04-30  127
2025-09-13  127
2025-09-19  127
...         ...
2025-04-05   54
2025-12-01   53
2025-02-01   52
2025-02-16   52
2025-07-01   49

[365 rows x 1 columns]

In [45]:
df['Date&Time'] = pd.to_datetime(df['Date&Time'])
df['Date'] = df['Date&Time'].dt.date
df['Time'] = df['Date&Time'].dt.time

/var/folders/5_/w6x2qs2n2dsg6mgnhkrxnzg00000gn/T/ipykernel_2105/1639901837.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date&Time'] = pd.to_datetime(df['Date&Time'])

In [46]:
df.head()

,SN,City,Municipality,Date&Time,Longitude,Latitude,Damage,Type,Description,Date,Time
0,1510533,BEOGRAD,BARAJEVO,2025-05-01 18:50:00,20.366175,44.619215,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Ostali sudari sa parkiranim vozilom,2025-05-01,18:50:00
1,1508366,BEOGRAD,BARAJEVO,2025-06-01 01:00:00,20.351757,44.604264,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Sudar sa parkiranim vozilom sa leve strane kol...,2025-06-01,01:00:00
2,1510854,BEOGRAD,BARAJEVO,2025-06-01 16:30:00,20.342381,44.588294,Sa povredjenim,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću istim putem ...,2025-06-01,16:30:00
3,1511079,BEOGRAD,BARAJEVO,2025-09-01 13:05:00,20.366297,44.618967,Sa mat.stetom,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću istim putem ...,2025-09-01,13:05:00
4,1508796,BEOGRAD,BARAJEVO,2025-11-01 02:30:00,20.413140,44.607341,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgode sa učešćem jednog vozila i životinja,2025-11-01,02:30:00

In [47]:
(
    df
    ["Date"]
    .value_counts()
    .to_frame("SN")
)

             SN
Date
2025-03-10  143
2025-08-11  131
2025-04-30  127
2025-09-13  127
2025-09-19  127
...         ...
2025-04-05   54
2025-12-01   53
2025-02-01   52
2025-02-16   52
2025-07-01   49

[365 rows x 1 columns]

In [64]:
df[df['Date'] == '2025-03-10']

Empty DataFrame
Columns: [SN, City, Municipality, Date&Time, Longitude, Latitude, Damage, Type, Description, Date, Time]
Index: []

In [44]:
(
    df
    ["City"]
    .value_counts()
    .to_frame("SN")
)

                      SN
City
BEOGRAD            14292
NOVI SAD            3119
NIŠ                 1321
SREMSKA MITROVICA   1229
ŠABAC               1082
KRAGUJEVAC           922
SMEDEREVO            841
KRUŠEVAC             825
POŽAREVAC            805
VALJEVO              795
PANČEVO              748
KRALJEVO             678
UŽICE                676
JAGODINA             650
ČAČAK                650
SOMBOR               615
VRANJE               593
ZRENJANIN            522
NOVI PAZAR           509
SUBOTICA             509
LESKOVAC             393
BOR                  389
KIKINDA              375
ZAJEČAR              320
PIROT                248
PROKUPLJE            157
PRIJEPOLJE           152

In [85]:
df_view = df[['City', 'Date']]
sorted_df = df_view.sort_values(by='City', ascending=True)
print(sorted_df)

          City        Date
0      BEOGRAD  2025-05-01
9523   BEOGRAD  2025-11-14
9524   BEOGRAD  2025-11-14
9525   BEOGRAD  2025-11-14
9526   BEOGRAD  2025-11-14
...        ...         ...
32699    ŠABAC  2025-01-11
32700    ŠABAC  2025-07-11
32701    ŠABAC  2025-08-11
32687    ŠABAC  2025-10-17
33414    ŠABAC  2025-12-28

[33415 rows x 2 columns]

In [91]:
df=pd.read_excel("2025.xlsx")

In [93]:
df.head()

,SN,City,Municipality,Date&Time,Longitude,Latitude,Damage,Type,Description
0,1510533,BEOGRAD,BARAJEVO,"05.01.2025,18:50",20.366175,44.619215,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Ostali sudari sa parkiranim vozilom
1,1508366,BEOGRAD,BARAJEVO,"06.01.2025,01:00",20.351757,44.604264,Sa mat.stetom,SN SA PARKIRANIM VOZILIMA,Sudar sa parkiranim vozilom sa leve strane kol...
2,1510854,BEOGRAD,BARAJEVO,"06.01.2025,16:30",20.342381,44.588294,Sa povredjenim,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću istim putem ...
3,1511079,BEOGRAD,BARAJEVO,"09.01.2025,13:05",20.366297,44.618967,Sa mat.stetom,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću istim putem ...
4,1508796,BEOGRAD,BARAJEVO,"11.01.2025,02:30",20.413140,44.607341,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgode sa učešćem jednog vozila i životinja

Empty DataFrame
Columns: [SN, City, Municipality, Date&Time, Longitude, Latitude, Damage, Type, Description]
Index: []

In [ ]:
df.groupby(['City','Date'])['SN'].count().unstack().plot(kind='bar')

In [41]:
df=pd.read_excel("2025.xlsx")

In [24]:
(
    df
    ["Time"]
    .value_counts()
    .to_frame("SN")
)

           SN
Time
18:00:00  467
15:00:00  455
17:00:00  437
13:00:00  423
14:00:00  414
...       ...
16:39:00    1
02:33:00    1
16:49:00    1
06:16:00    1
21:12:00    1

[1192 rows x 1 columns]

In [57]:
df[df['Date'].isin([2025-0o3-10])]

Empty DataFrame
Columns: [SN, City, Municipality, Date&Time, Longitude, Latitude, Damage, Type, Description, Date, Time]
Index: []

In [95]:
df.pivot_table(index='City', columns='Damage', values='SN', aggfunc='count')

Damage             Sa mat.stetom  Sa poginulim  Sa povredjenim
City
BEOGRAD                    10731            88            3473
BOR                          217            16             156
JAGODINA                     355            13             282
KIKINDA                      191             6             178
KRAGUJEVAC                   396            23             503
KRALJEVO                     312            17             349
KRUŠEVAC                     380            14             431
LESKOVAC                     142            11             240
NIŠ                          693            19             609
NOVI PAZAR                   220             3             286
NOVI SAD                    1493            43            1583
PANČEVO                      237            27             484
PIROT                        109             6             133
POŽAREVAC                    448            15             342
PRIJEPOLJE                    74             4              74
PROKUPLJE                     63             4              90
SMEDEREVO                    466            12             363
SOMBOR                       259            12             344
SREMSKA MITROVICA            510            26             693
SUBOTICA                     239             7             263
UŽICE                        370            12             294
VALJEVO                      431            12             352
VRANJE                       380             9             204
ZAJEČAR                      178             8             134
ZRENJANIN                    186            14             322
ČAČAK                        251            19             380
ŠABAC                        488            23             571

In [103]:
df.pivot_table(index='Date', columns='City', values='SN', aggfunc='count')

City,BEOGRAD,BOR,JAGODINA,KIKINDA,KRAGUJEVAC,KRALJEVO,KRUŠEVAC,LESKOVAC,NIŠ,NOVI PAZAR,...,SOMBOR,SREMSKA MITROVICA,SUBOTICA,UŽICE,VALJEVO,VRANJE,ZAJEČAR,ZRENJANIN,ČAČAK,ŠABAC
Date,,,,,,,,,,,,,,,,,,,,,
2025-01-01,28.0,NaN,2.0,2.0,3.0,2.0,NaN,1.0,3.0,2.0,...,NaN,9.0,3.0,2.0,3.0,6.0,1.0,1.0,1.0,3.0
2025-01-02,26.0,1.0,1.0,NaN,2.0,2.0,2.0,NaN,5.0,1.0,...,NaN,3.0,NaN,1.0,4.0,NaN,1.0,NaN,NaN,3.0
2025-01-03,37.0,1.0,1.0,1.0,NaN,1.0,2.0,NaN,5.0,1.0,...,1.0,3.0,NaN,1.0,2.0,2.0,1.0,2.0,2.0,6.0
2025-01-04,46.0,1.0,1.0,1.0,1.0,NaN,3.0,NaN,2.0,1.0,...,1.0,4.0,2.0,1.0,5.0,2.0,1.0,NaN,1.0,2.0
2025-01-05,30.0,2.0,3.0,1.0,2.0,1.0,NaN,NaN,5.0,NaN,...,2.0,5.0,3.0,4.0,3.0,2.0,NaN,1.0,NaN,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-12-27,42.0,2.0,5.0,2.0,4.0,NaN,1.0,1.0,2.0,NaN,...,1.0,1.0,4.0,5.0,1.0,1.0,NaN,2.0,1.0,2.0
2025-12-28,22.0,1.0,3.0,NaN,2.0,4.0,1.0,3.0,1.0,1.0,...,2.0,1.0,2.0,3.0,4.0,1.0,NaN,NaN,NaN,2.0
2025-12-29,74.0,2.0,4.0,2.0,2.0,3.0,3.0,2.0,3.0,1.0,...,1.0,5.0,NaN,1.0,1.0,3.0,NaN,1.0,1.0,NaN
2025-12-30,48.0,1.0,NaN,1.0,2.0,1.0,1.0,NaN,6.0,2.0,...,1.0,4.0,2.0,4.0,NaN,1.0,NaN,NaN,1.0,NaN
2025-12-31,49.0,NaN,1.0,NaN,5.0,1.0,2.0,NaN,3.0,2.0,...,6.0,4.0,NaN,2.0,3.0,1.0,1.0,1.0,2.0,2.0